name = "backend"
compatibility_date = "2024-08-16"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzcxMWRlZGItMzE5OC00NDhkLWI3ZTYtMGY3NGFiZGMyZjMxIiwidGVuYW50X2lkIjoiOWI4ODJjMmJlNTg3ZTNiZWU2ZmRlYTllMjFmOWE5MzI5NTdkNmMxZWZhNGYzNjdjYmY5NWZjNGUyYTc2N2Y0MyIsImludGVybmFsX3NlY3JldCI6ImZiNDEyOTM2LTljZGQtNDk2Ny1hZDM2LTFkNDhhZTljNmUwNiJ9.yRL3hr3M7SGH_zfz8Z_8VCg58eKWoNCffPP5KiVX_TI"
JWT_SECRET = "JWT_SEC_PASSWORD"