name = "backend"
compatibility_date = "2024-08-16"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZGRlMGJmODYtYjljZS00ZTM1LTg0NWQtMDA1MjExOGY1YmNjIiwidGVuYW50X2lkIjoiNTg3ZjZlODVmM2YzMDJiNTBlNTE3MzI0ODIwMzUzOTUyMTExNWI2ZmZmNzkyM2ZlZjQyNjc3OGY0Y2JjNmRjNiIsImludGVybmFsX3NlY3JldCI6ImM4MTJiYjNlLThhYjgtNDMwNS05Y2ZiLTI5YjY4ZjgxNmE0ZiJ9.iQMt9SzVbBiffVCY6uw_C_WjU2k0Bmjllo9DH0DAB4E"
JWT_SECRET="Shhh..."